// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: admin_service.proto

package drghs_v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Request message for [DevRelServicesAdmin.UpdateTrackedRepos].
type UpdateTrackedReposRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTrackedReposRequest) Reset() {
	*x = UpdateTrackedReposRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrackedReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrackedReposRequest) ProtoMessage() {}

func (x *UpdateTrackedReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrackedReposRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrackedReposRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0}
}

// Response message for [DevRelServicesAdmin.UpdateTrackedRepos].
type UpdateTrackedReposResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTrackedReposResponse) Reset() {
	*x = UpdateTrackedReposResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrackedReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrackedReposResponse) ProtoMessage() {}

func (x *UpdateTrackedReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrackedReposResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrackedReposResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{1}
}

var File_admin_service_proto protoreflect.FileDescriptor

var file_admin_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x72, 0x67, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65,
	0x70, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8e, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x76,
	0x52, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x77, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x12, 0x23, 0x2e, 0x64, 0x72, 0x67, 0x68, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x72,
	0x67, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_admin_service_proto_rawDescOnce sync.Once
	file_admin_service_proto_rawDescData = file_admin_service_proto_rawDesc
)

func file_admin_service_proto_rawDescGZIP() []byte {
	file_admin_service_proto_rawDescOnce.Do(func() {
		file_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_service_proto_rawDescData)
	})
	return file_admin_service_proto_rawDescData
}

var file_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_service_proto_goTypes = []interface{}{
	(*UpdateTrackedReposRequest)(nil),  // 0: drghs.v1.UpdateTrackedReposRequest
	(*UpdateTrackedReposResponse)(nil), // 1: drghs.v1.UpdateTrackedReposResponse
}
var file_admin_service_proto_depIdxs = []int32{
	0, // 0: drghs.v1.DevRelServicesAdmin.UpdateTrackedRepos:input_type -> drghs.v1.UpdateTrackedReposRequest
	1, // 1: drghs.v1.DevRelServicesAdmin.UpdateTrackedRepos:output_type -> drghs.v1.UpdateTrackedReposResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_service_proto_init() }
func file_admin_service_proto_init() {
	if File_admin_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrackedReposRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrackedReposResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_service_proto_goTypes,
		DependencyIndexes: file_admin_service_proto_depIdxs,
		MessageInfos:      file_admin_service_proto_msgTypes,
	}.Build()
	File_admin_service_proto = out.File
	file_admin_service_proto_rawDesc = nil
	file_admin_service_proto_goTypes = nil
	file_admin_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DevRelServicesAdminClient is the client API for DevRelServicesAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevRelServicesAdminClient interface {
	UpdateTrackedRepos(ctx context.Context, in *UpdateTrackedReposRequest, opts ...grpc.CallOption) (*UpdateTrackedReposResponse, error)
}

type devRelServicesAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewDevRelServicesAdminClient(cc grpc.ClientConnInterface) DevRelServicesAdminClient {
	return &devRelServicesAdminClient{cc}
}

func (c *devRelServicesAdminClient) UpdateTrackedRepos(ctx context.Context, in *UpdateTrackedReposRequest, opts ...grpc.CallOption) (*UpdateTrackedReposResponse, error) {
	out := new(UpdateTrackedReposResponse)
	err := c.cc.Invoke(ctx, "/drghs.v1.DevRelServicesAdmin/UpdateTrackedRepos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevRelServicesAdminServer is the server API for DevRelServicesAdmin service.
type DevRelServicesAdminServer interface {
	UpdateTrackedRepos(context.Context, *UpdateTrackedReposRequest) (*UpdateTrackedReposResponse, error)
}

// UnimplementedDevRelServicesAdminServer can be embedded to have forward compatible implementations.
type UnimplementedDevRelServicesAdminServer struct {
}

func (*UnimplementedDevRelServicesAdminServer) UpdateTrackedRepos(context.Context, *UpdateTrackedReposRequest) (*UpdateTrackedReposResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrackedRepos not implemented")
}

func RegisterDevRelServicesAdminServer(s *grpc.Server, srv DevRelServicesAdminServer) {
	s.RegisterService(&_DevRelServicesAdmin_serviceDesc, srv)
}

func _DevRelServicesAdmin_UpdateTrackedRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrackedReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevRelServicesAdminServer).UpdateTrackedRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drghs.v1.DevRelServicesAdmin/UpdateTrackedRepos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevRelServicesAdminServer).UpdateTrackedRepos(ctx, req.(*UpdateTrackedReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DevRelServicesAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drghs.v1.DevRelServicesAdmin",
	HandlerType: (*DevRelServicesAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTrackedRepos",
			Handler:    _DevRelServicesAdmin_UpdateTrackedRepos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_service.proto",
}
