// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_service.proto

package drghs_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for [DevRelServicesAdmin.UpdateTrackedRepos].
type UpdateTrackedReposRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTrackedReposRequest) Reset()         { *m = UpdateTrackedReposRequest{} }
func (m *UpdateTrackedReposRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTrackedReposRequest) ProtoMessage()    {}
func (*UpdateTrackedReposRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{0}
}

func (m *UpdateTrackedReposRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTrackedReposRequest.Unmarshal(m, b)
}
func (m *UpdateTrackedReposRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTrackedReposRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTrackedReposRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTrackedReposRequest.Merge(m, src)
}
func (m *UpdateTrackedReposRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTrackedReposRequest.Size(m)
}
func (m *UpdateTrackedReposRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTrackedReposRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTrackedReposRequest proto.InternalMessageInfo

// Response message for [DevRelServicesAdmin.UpdateTrackedRepos].
type UpdateTrackedReposResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTrackedReposResponse) Reset()         { *m = UpdateTrackedReposResponse{} }
func (m *UpdateTrackedReposResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTrackedReposResponse) ProtoMessage()    {}
func (*UpdateTrackedReposResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{1}
}

func (m *UpdateTrackedReposResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTrackedReposResponse.Unmarshal(m, b)
}
func (m *UpdateTrackedReposResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTrackedReposResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTrackedReposResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTrackedReposResponse.Merge(m, src)
}
func (m *UpdateTrackedReposResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTrackedReposResponse.Size(m)
}
func (m *UpdateTrackedReposResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTrackedReposResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTrackedReposResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpdateTrackedReposRequest)(nil), "drghs.v1.UpdateTrackedReposRequest")
	proto.RegisterType((*UpdateTrackedReposResponse)(nil), "drghs.v1.UpdateTrackedReposResponse")
}

func init() {
	proto.RegisterFile("admin_service.proto", fileDescriptor_f9bc00259dc38d22)
}

var fileDescriptor_f9bc00259dc38d22 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4c, 0xc9, 0xcd,
	0xcc, 0x8b, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x48, 0x29, 0x4a, 0xcf, 0x28, 0xd6, 0x2b, 0x33, 0x94, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf,
	0x2b, 0x86, 0xa8, 0x53, 0x92, 0xe6, 0x92, 0x0c, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x0d, 0x29, 0x4a,
	0x4c, 0xce, 0x4e, 0x4d, 0x09, 0x4a, 0x2d, 0xc8, 0x2f, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x51, 0x92, 0xe1, 0x92, 0xc2, 0x26, 0x59, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x6a, 0xd4, 0xc7, 0xc8,
	0x25, 0xec, 0x92, 0x5a, 0x16, 0x94, 0x9a, 0x13, 0x0c, 0xb1, 0xba, 0xd8, 0x11, 0xe4, 0x10, 0xa1,
	0x72, 0x2e, 0x21, 0x4c, 0x5d, 0x42, 0xca, 0x7a, 0x30, 0x17, 0xe9, 0xe1, 0xb4, 0x50, 0x4a, 0x05,
	0xbf, 0x22, 0x88, 0xc5, 0x4a, 0x62, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x12, 0x50, 0xe2, 0x03, 0xfb,
	0xa9, 0xcc, 0x50, 0xbf, 0x14, 0xac, 0x36, 0x89, 0x0d, 0xec, 0x25, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x99, 0x9a, 0xe0, 0x11, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DevRelServicesAdminClient is the client API for DevRelServicesAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevRelServicesAdminClient interface {
	UpdateTrackedRepos(ctx context.Context, in *UpdateTrackedReposRequest, opts ...grpc.CallOption) (*UpdateTrackedReposResponse, error)
}

type devRelServicesAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewDevRelServicesAdminClient(cc grpc.ClientConnInterface) DevRelServicesAdminClient {
	return &devRelServicesAdminClient{cc}
}

func (c *devRelServicesAdminClient) UpdateTrackedRepos(ctx context.Context, in *UpdateTrackedReposRequest, opts ...grpc.CallOption) (*UpdateTrackedReposResponse, error) {
	out := new(UpdateTrackedReposResponse)
	err := c.cc.Invoke(ctx, "/drghs.v1.DevRelServicesAdmin/UpdateTrackedRepos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevRelServicesAdminServer is the server API for DevRelServicesAdmin service.
type DevRelServicesAdminServer interface {
	UpdateTrackedRepos(context.Context, *UpdateTrackedReposRequest) (*UpdateTrackedReposResponse, error)
}

// UnimplementedDevRelServicesAdminServer can be embedded to have forward compatible implementations.
type UnimplementedDevRelServicesAdminServer struct {
}

func (*UnimplementedDevRelServicesAdminServer) UpdateTrackedRepos(ctx context.Context, req *UpdateTrackedReposRequest) (*UpdateTrackedReposResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrackedRepos not implemented")
}

func RegisterDevRelServicesAdminServer(s *grpc.Server, srv DevRelServicesAdminServer) {
	s.RegisterService(&_DevRelServicesAdmin_serviceDesc, srv)
}

func _DevRelServicesAdmin_UpdateTrackedRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrackedReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevRelServicesAdminServer).UpdateTrackedRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drghs.v1.DevRelServicesAdmin/UpdateTrackedRepos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevRelServicesAdminServer).UpdateTrackedRepos(ctx, req.(*UpdateTrackedReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DevRelServicesAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drghs.v1.DevRelServicesAdmin",
	HandlerType: (*DevRelServicesAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTrackedRepos",
			Handler:    _DevRelServicesAdmin_UpdateTrackedRepos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_service.proto",
}
