// Code generated by protoc-gen-go. DO NOT EDIT.
// source: issue_service_internal.proto

package maintner_internal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TombstoneIssueRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	IssueNumber          int32    `protobuf:"varint,2,opt,name=issue_number,json=issueNumber,proto3" json:"issue_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneIssueRequest) Reset()         { *m = TombstoneIssueRequest{} }
func (m *TombstoneIssueRequest) String() string { return proto.CompactTextString(m) }
func (*TombstoneIssueRequest) ProtoMessage()    {}
func (*TombstoneIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9459a83d0b98bca9, []int{0}
}

func (m *TombstoneIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneIssueRequest.Unmarshal(m, b)
}
func (m *TombstoneIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneIssueRequest.Marshal(b, m, deterministic)
}
func (m *TombstoneIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneIssueRequest.Merge(m, src)
}
func (m *TombstoneIssueRequest) XXX_Size() int {
	return xxx_messageInfo_TombstoneIssueRequest.Size(m)
}
func (m *TombstoneIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneIssueRequest proto.InternalMessageInfo

func (m *TombstoneIssueRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *TombstoneIssueRequest) GetIssueNumber() int32 {
	if m != nil {
		return m.IssueNumber
	}
	return 0
}

type TombstoneIssueResponse struct {
	NumberTombstoned     int32    `protobuf:"varint,1,opt,name=number_tombstoned,json=numberTombstoned,proto3" json:"number_tombstoned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneIssueResponse) Reset()         { *m = TombstoneIssueResponse{} }
func (m *TombstoneIssueResponse) String() string { return proto.CompactTextString(m) }
func (*TombstoneIssueResponse) ProtoMessage()    {}
func (*TombstoneIssueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9459a83d0b98bca9, []int{1}
}

func (m *TombstoneIssueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneIssueResponse.Unmarshal(m, b)
}
func (m *TombstoneIssueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneIssueResponse.Marshal(b, m, deterministic)
}
func (m *TombstoneIssueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneIssueResponse.Merge(m, src)
}
func (m *TombstoneIssueResponse) XXX_Size() int {
	return xxx_messageInfo_TombstoneIssueResponse.Size(m)
}
func (m *TombstoneIssueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneIssueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneIssueResponse proto.InternalMessageInfo

func (m *TombstoneIssueResponse) GetNumberTombstoned() int32 {
	if m != nil {
		return m.NumberTombstoned
	}
	return 0
}

func init() {
	proto.RegisterType((*TombstoneIssueRequest)(nil), "maintner.internal.TombstoneIssueRequest")
	proto.RegisterType((*TombstoneIssueResponse)(nil), "maintner.internal.TombstoneIssueResponse")
}

func init() { proto.RegisterFile("issue_service_internal.proto", fileDescriptor_9459a83d0b98bca9) }

var fileDescriptor_9459a83d0b98bca9 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x2c, 0x2e, 0x2e,
	0x4d, 0x8d, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x8d, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca,
	0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcc, 0x4d, 0xcc, 0xcc, 0x2b, 0xc9,
	0x4b, 0x2d, 0xd2, 0x83, 0x49, 0x28, 0x05, 0x71, 0x89, 0x86, 0xe4, 0xe7, 0x26, 0x15, 0x97, 0xe4,
	0xe7, 0xa5, 0x7a, 0x82, 0xf4, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71, 0xb1,
	0x15, 0x24, 0x16, 0xa5, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42,
	0x8a, 0x5c, 0x3c, 0x10, 0x3b, 0xf2, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x24, 0x98, 0x14, 0x18, 0x35,
	0x58, 0x83, 0xb8, 0xc1, 0x62, 0x7e, 0x60, 0x21, 0x25, 0x57, 0x2e, 0x31, 0x74, 0x33, 0x8b, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xb4, 0xb9, 0x04, 0x21, 0xda, 0xe2, 0x4b, 0x60, 0x0a, 0x52, 0xc0,
	0xe6, 0xb3, 0x06, 0x09, 0x40, 0x24, 0xe0, 0x1a, 0x53, 0x8c, 0x9a, 0x18, 0xb9, 0x44, 0x3c, 0xa1,
	0xee, 0x04, 0x1b, 0x13, 0x0c, 0xf1, 0x95, 0x50, 0x16, 0x17, 0x3f, 0xaa, 0xf9, 0xc5, 0x42, 0x1a,
	0x7a, 0x18, 0x5e, 0xd3, 0xc3, 0xea, 0x2f, 0x29, 0x4d, 0x22, 0x54, 0x42, 0x5c, 0xab, 0xc4, 0xa0,
	0xc1, 0x98, 0xc4, 0x06, 0x0e, 0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x0f, 0x9f,
	0x48, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalIssueServiceClient is the client API for InternalIssueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalIssueServiceClient interface {
	TombstoneIssues(ctx context.Context, opts ...grpc.CallOption) (InternalIssueService_TombstoneIssuesClient, error)
}

type internalIssueServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalIssueServiceClient(cc *grpc.ClientConn) InternalIssueServiceClient {
	return &internalIssueServiceClient{cc}
}

func (c *internalIssueServiceClient) TombstoneIssues(ctx context.Context, opts ...grpc.CallOption) (InternalIssueService_TombstoneIssuesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InternalIssueService_serviceDesc.Streams[0], "/maintner.internal.InternalIssueService/TombstoneIssues", opts...)
	if err != nil {
		return nil, err
	}
	x := &internalIssueServiceTombstoneIssuesClient{stream}
	return x, nil
}

type InternalIssueService_TombstoneIssuesClient interface {
	Send(*TombstoneIssueRequest) error
	CloseAndRecv() (*TombstoneIssueResponse, error)
	grpc.ClientStream
}

type internalIssueServiceTombstoneIssuesClient struct {
	grpc.ClientStream
}

func (x *internalIssueServiceTombstoneIssuesClient) Send(m *TombstoneIssueRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *internalIssueServiceTombstoneIssuesClient) CloseAndRecv() (*TombstoneIssueResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TombstoneIssueResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InternalIssueServiceServer is the server API for InternalIssueService service.
type InternalIssueServiceServer interface {
	TombstoneIssues(InternalIssueService_TombstoneIssuesServer) error
}

// UnimplementedInternalIssueServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInternalIssueServiceServer struct {
}

func (*UnimplementedInternalIssueServiceServer) TombstoneIssues(srv InternalIssueService_TombstoneIssuesServer) error {
	return status.Errorf(codes.Unimplemented, "method TombstoneIssues not implemented")
}

func RegisterInternalIssueServiceServer(s *grpc.Server, srv InternalIssueServiceServer) {
	s.RegisterService(&_InternalIssueService_serviceDesc, srv)
}

func _InternalIssueService_TombstoneIssues_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InternalIssueServiceServer).TombstoneIssues(&internalIssueServiceTombstoneIssuesServer{stream})
}

type InternalIssueService_TombstoneIssuesServer interface {
	SendAndClose(*TombstoneIssueResponse) error
	Recv() (*TombstoneIssueRequest, error)
	grpc.ServerStream
}

type internalIssueServiceTombstoneIssuesServer struct {
	grpc.ServerStream
}

func (x *internalIssueServiceTombstoneIssuesServer) SendAndClose(m *TombstoneIssueResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *internalIssueServiceTombstoneIssuesServer) Recv() (*TombstoneIssueRequest, error) {
	m := new(TombstoneIssueRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _InternalIssueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maintner.internal.InternalIssueService",
	HandlerType: (*InternalIssueServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TombstoneIssues",
			Handler:       _InternalIssueService_TombstoneIssues_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "issue_service_internal.proto",
}
