// Code generated by protoc-gen-go. DO NOT EDIT.
// source: issue_service_internal.proto

package maintner_internal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TombstoneIssuesRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	IssueNumbers         []int32  `protobuf:"varint,2,rep,packed,name=issue_numbers,json=issueNumbers,proto3" json:"issue_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneIssuesRequest) Reset()         { *m = TombstoneIssuesRequest{} }
func (m *TombstoneIssuesRequest) String() string { return proto.CompactTextString(m) }
func (*TombstoneIssuesRequest) ProtoMessage()    {}
func (*TombstoneIssuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9459a83d0b98bca9, []int{0}
}

func (m *TombstoneIssuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneIssuesRequest.Unmarshal(m, b)
}
func (m *TombstoneIssuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneIssuesRequest.Marshal(b, m, deterministic)
}
func (m *TombstoneIssuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneIssuesRequest.Merge(m, src)
}
func (m *TombstoneIssuesRequest) XXX_Size() int {
	return xxx_messageInfo_TombstoneIssuesRequest.Size(m)
}
func (m *TombstoneIssuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneIssuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneIssuesRequest proto.InternalMessageInfo

func (m *TombstoneIssuesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *TombstoneIssuesRequest) GetIssueNumbers() []int32 {
	if m != nil {
		return m.IssueNumbers
	}
	return nil
}

type TombstoneIssuesResponse struct {
	TombstonedCount      int32    `protobuf:"varint,1,opt,name=tombstoned_count,json=tombstonedCount,proto3" json:"tombstoned_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneIssuesResponse) Reset()         { *m = TombstoneIssuesResponse{} }
func (m *TombstoneIssuesResponse) String() string { return proto.CompactTextString(m) }
func (*TombstoneIssuesResponse) ProtoMessage()    {}
func (*TombstoneIssuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9459a83d0b98bca9, []int{1}
}

func (m *TombstoneIssuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneIssuesResponse.Unmarshal(m, b)
}
func (m *TombstoneIssuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneIssuesResponse.Marshal(b, m, deterministic)
}
func (m *TombstoneIssuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneIssuesResponse.Merge(m, src)
}
func (m *TombstoneIssuesResponse) XXX_Size() int {
	return xxx_messageInfo_TombstoneIssuesResponse.Size(m)
}
func (m *TombstoneIssuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneIssuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneIssuesResponse proto.InternalMessageInfo

func (m *TombstoneIssuesResponse) GetTombstonedCount() int32 {
	if m != nil {
		return m.TombstonedCount
	}
	return 0
}

func init() {
	proto.RegisterType((*TombstoneIssuesRequest)(nil), "maintner.internal.TombstoneIssuesRequest")
	proto.RegisterType((*TombstoneIssuesResponse)(nil), "maintner.internal.TombstoneIssuesResponse")
}

func init() { proto.RegisterFile("issue_service_internal.proto", fileDescriptor_9459a83d0b98bca9) }

var fileDescriptor_9459a83d0b98bca9 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x2c, 0x2e, 0x2e,
	0x4d, 0x8d, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x8d, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca,
	0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcc, 0x4d, 0xcc, 0xcc, 0x2b, 0xc9,
	0x4b, 0x2d, 0xd2, 0x83, 0x49, 0x28, 0x85, 0x72, 0x89, 0x85, 0xe4, 0xe7, 0x26, 0x15, 0x97, 0xe4,
	0xe7, 0xa5, 0x7a, 0x82, 0xf4, 0x16, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71,
	0xb1, 0x15, 0x24, 0x16, 0xa5, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79,
	0x42, 0xca, 0x5c, 0xbc, 0x10, 0x4b, 0xf2, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x8a, 0x25, 0x98, 0x14,
	0x98, 0x35, 0x58, 0x83, 0x78, 0xc0, 0x82, 0x7e, 0x10, 0x31, 0x25, 0x17, 0x2e, 0x71, 0x0c, 0x63,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x34, 0xb9, 0x04, 0x4a, 0x60, 0x52, 0x29, 0xf1, 0xc9,
	0xf9, 0xa5, 0x50, 0x1b, 0x58, 0x83, 0xf8, 0x11, 0xe2, 0xce, 0x20, 0x61, 0xa3, 0x26, 0x46, 0x2e,
	0x11, 0x4f, 0xa8, 0x4b, 0xc1, 0xa6, 0x04, 0x43, 0xfc, 0x25, 0x94, 0xc5, 0xc5, 0x8f, 0x66, 0xbc,
	0x90, 0xa6, 0x1e, 0x86, 0xe7, 0xf4, 0xb0, 0xfb, 0x4c, 0x4a, 0x8b, 0x18, 0xa5, 0x10, 0xd7, 0x2a,
	0x31, 0x24, 0xb1, 0x81, 0xc3, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x7d, 0x9d, 0x66,
	0x5b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalIssueServiceClient is the client API for InternalIssueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalIssueServiceClient interface {
	TombstoneIssues(ctx context.Context, in *TombstoneIssuesRequest, opts ...grpc.CallOption) (*TombstoneIssuesResponse, error)
}

type internalIssueServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalIssueServiceClient(cc *grpc.ClientConn) InternalIssueServiceClient {
	return &internalIssueServiceClient{cc}
}

func (c *internalIssueServiceClient) TombstoneIssues(ctx context.Context, in *TombstoneIssuesRequest, opts ...grpc.CallOption) (*TombstoneIssuesResponse, error) {
	out := new(TombstoneIssuesResponse)
	err := c.cc.Invoke(ctx, "/maintner.internal.InternalIssueService/TombstoneIssues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalIssueServiceServer is the server API for InternalIssueService service.
type InternalIssueServiceServer interface {
	TombstoneIssues(context.Context, *TombstoneIssuesRequest) (*TombstoneIssuesResponse, error)
}

// UnimplementedInternalIssueServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInternalIssueServiceServer struct {
}

func (*UnimplementedInternalIssueServiceServer) TombstoneIssues(ctx context.Context, req *TombstoneIssuesRequest) (*TombstoneIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TombstoneIssues not implemented")
}

func RegisterInternalIssueServiceServer(s *grpc.Server, srv InternalIssueServiceServer) {
	s.RegisterService(&_InternalIssueService_serviceDesc, srv)
}

func _InternalIssueService_TombstoneIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TombstoneIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalIssueServiceServer).TombstoneIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maintner.internal.InternalIssueService/TombstoneIssues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalIssueServiceServer).TombstoneIssues(ctx, req.(*TombstoneIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalIssueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maintner.internal.InternalIssueService",
	HandlerType: (*InternalIssueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TombstoneIssues",
			Handler:    _InternalIssueService_TombstoneIssues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "issue_service_internal.proto",
}
