// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: issue_service.proto

module devrel/cloud/devrel-github-service/drghs

require (
	github.com/golang/protobuf v1.2.0
	golang.org/x/net v0.0.0-20181220203305-927f97764cc3
	google.golang.org/genproto v0.0.0-20181221175505-bd9b4fb69e2f
	google.golang.org/grpc v1.17.0
)
