on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    # Install dependencies
    - uses: actions/cache@v1
      id: cache-deps
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install dependencies
      run: ./go.get.sh
    # Lint
    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        golint -set_exit_status ./...
    # Test
    - name: "Test"
      run: ./go.test.sh
    # Integration Tests
    - name: "Integration"
      run: ./go.integration.test.sh
    # Upload code coverage
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
